"""make permission name unique

Revision ID: 23eba57f8b54
Revises: 97f58b6f454d
Create Date: 2026-04-07 21:34:38.041998

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "23eba57f8b54"
down_revision: Union[str, Sequence[str], None] = "97f58b6f454d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('order_items')
    # op.drop_table('orders')
    op.create_unique_constraint(None, "permissions", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "permissions", type_="unique")
    op.create_table(
        "orders",
        sa.Column("id", sa.VARCHAR(length=60), autoincrement=False, nullable=False),
        sa.Column(
            "total_amount",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("status", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "cart_id", sa.VARCHAR(length=60), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["cart_id"], ["carts.id"], name=op.f("orders_cart_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("orders_pkey")),
    )
    op.create_table(
        "order_items",
        sa.Column("id", sa.VARCHAR(length=60), autoincrement=False, nullable=False),
        sa.Column(
            "product_id", sa.VARCHAR(length=60), autoincrement=False, nullable=True
        ),
        sa.Column("quantity", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "price",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("image_url", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "order_id", sa.VARCHAR(length=60), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("order_items_order_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("order_items_pkey")),
    )
    # ### end Alembic commands ###
