"""add name to CartItem

Revision ID: 47666be1f4df
Revises: 
Create Date: 2026-04-01 23:09:46.253501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47666be1f4df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carts')
    op.drop_table('cartitems')
    op.drop_table('users')
    op.drop_table('user_roles')
    op.drop_table('orders')
    op.drop_table('user_addresses')
    op.drop_table('product_images')
    op.drop_table('addresses')
    op.drop_table('categories')
    op.drop_table('products')
    op.drop_table('permissions')
    op.drop_table('role_permissions')
    op.drop_table('order_items')
    op.drop_table('roles')
    op.drop_table('inventories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventories',
    sa.Column('id', sa.VARCHAR(length=60), nullable=False),
    sa.Column('product_id', sa.VARCHAR(length=60), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('reserved_quantity', sa.INTEGER(), nullable=False),
    sa.Column('cost_price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('selling_price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('location', sa.VARCHAR(length=60), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location')
    )
    op.create_table('roles',
    sa.Column('id', sa.VARCHAR(length=60), nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('order_items',
    sa.Column('id', sa.VARCHAR(length=60), nullable=False),
    sa.Column('product_id', sa.VARCHAR(length=60), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('image_url', sa.VARCHAR(), nullable=True),
    sa.Column('order_id', sa.VARCHAR(length=60), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('role_id', sa.VARCHAR(length=60), nullable=False),
    sa.Column('permission_id', sa.VARCHAR(length=60), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.VARCHAR(length=60), nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), nullable=False),
    sa.Column('action', sa.VARCHAR(length=15), nullable=False),
    sa.Column('target', sa.VARCHAR(length=15), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.VARCHAR(length=60), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('category_name', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['category_name'], ['categories.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.VARCHAR(length=60), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('addresses',
    sa.Column('id', sa.VARCHAR(length=60), nullable=False),
    sa.Column('city', sa.VARCHAR(length=150), nullable=True),
    sa.Column('county', sa.VARCHAR(), nullable=True),
    sa.Column('ward', sa.VARCHAR(), nullable=True),
    sa.Column('street', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('address', sa.VARCHAR(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_images',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('file_name', sa.VARCHAR(), nullable=False),
    sa.Column('is_main', sa.BOOLEAN(), nullable=True),
    sa.Column('product_id', sa.VARCHAR(), nullable=False),
    sa.Column('uploaded_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name'),
    sa.UniqueConstraint('url')
    )
    op.create_table('user_addresses',
    sa.Column('user_id', sa.VARCHAR(length=60), nullable=False),
    sa.Column('address_id', sa.VARCHAR(length=60), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'address_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.VARCHAR(length=60), nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('cart_id', sa.VARCHAR(length=60), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('role_id', sa.VARCHAR(length=60), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=60), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'user_id')
    )
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(length=60), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=60), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('cartitems',
    sa.Column('id', sa.VARCHAR(length=60), nullable=False),
    sa.Column('product_id', sa.VARCHAR(length=60), nullable=True),
    sa.Column('cart_id', sa.VARCHAR(length=60), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('image_url', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carts',
    sa.Column('id', sa.VARCHAR(length=60), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=60), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###
